#!/usr/bin/env bash
# The `jsontolang-wasm` workspace package = crates/wasm/pkg/, generated by
# wasm-pack and gitignored. Without it `pnpm install` fails to resolve
# `jsontolang-wasm@workspace:*`. pnpm 11 also runs a deps-verify before every
# `pnpm run <script>`, so this MUST be run directly (bash setup.sh), NOT via
# pnpm.
#
# Prereqs: Rust toolchain + wasm-pack on PATH (cargo install wasm-pack).
set -euo pipefail
cd "$(dirname "$0")"

echo "==> Building wasm package (crates/wasm/pkg)"
(cd crates/wasm && wasm-pack build --target web)

echo "==> Copying jsontolang_wasm_bg.wasm into apps/web/public"
mkdir -p apps/web/public
cp crates/wasm/pkg/jsontolang_wasm_bg.wasm apps/web/public/jsontolang_wasm_bg.wasm

echo "==> Copying Lua plugins into apps/web/public/lua"
mkdir -p apps/web/public/lua
cp crates/cli/plugins/*.lua apps/web/public/lua/

echo "==> pnpm install"
pnpm install

echo "==> Done. Run: pnpm dev"
