#!/usr/bin/env bash
# The `wasm` workspace package = crates/wasm/pkg/, generated by wasm-pack and
# gitignored. Without it `pnpm install` fails to resolve `wasm@workspace:*`.
# pnpm 11 also runs a deps-verify before every `pnpm run <script>`, so this
# MUST be run directly (bash setup.sh), NOT via pnpm.
#
# Prereqs: Rust toolchain + wasm-pack on PATH (cargo install wasm-pack).
set -euo pipefail
cd "$(dirname "$0")"

echo "==> Building wasm package (crates/wasm/pkg)"
(cd crates/wasm && wasm-pack build --target web)

echo "==> Copying wasm_bg.wasm into apps/web/public"
mkdir -p apps/web/public
cp crates/wasm/pkg/wasm_bg.wasm apps/web/public/wasm_bg.wasm

echo "==> pnpm install"
pnpm install

echo "==> Done. Run: pnpm dev"
