[package]
name = "jsontolang-tui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "jsontolang-tui"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
arboard = "3.6.1"
jsontolang-core = { workspace = true }
ratatui = "0.30.2"
ratatui-textarea = "0.9.2"
serde_json = { workspace = true }
